name: 'ottr-reports'
author: "Candace Savonen"
description: "Run OTTR checks for spelling, urls, and quiz formats"

inputs:
  check_type:
    description: "There are three types of reports that can be done and specified: 'spelling', 'urls', or 'quiz_format'."
    required: true
    type: string
  error_min:
    description: "What number of errors should make this check fail?"
    default: 0
    type: number

outputs:
  error_name:
    description: "The name of the error that was run"
    type: string
  report_path:
    description: "The relative path to where the report was saved."
    type: string
  error_num:
    description: "How many errors were found."
    type: number 

runs:
  using: 'docker'
  image: 'docker://jhudsl/ottr-reports'
  args:
    - ${{ inputs.check_type }}
    - ${{ inputs.error_min }}

branding:
  icon: "briefcase"
  color: "blue"
