# Candace Savonen Dec 2021

name: Test ottr reports

on:
  pull_request:
    branches: [ main ]

jobs:

  do-the-job:
    name: Test ottr-reports
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       with:
         fetch-depth: 0

    - name: Check spelling
      uses: ./
      with:
        check_type: "spelling"
        error_min: 3

    - name: Check URLs
      uses: ./
      with:
        check_type: "urls"
        error_min: 0

    - name: Check quiz formatting
      uses: ./
      with:
        check_type: "quiz_format"
        error_min: 0
