# Candace Savonen Mar 2022

name: Testing ottr-reports
on:
  pull_request:
    branches: [ main ]

jobs:

  check-out-repo:
    name: Check out OTTR_Template repo
    uses: actions/checkout@v2
    with:
      repository: jhudsl/OTTR_Template
      fetch-depth: 0

  spell-check:
    name: Check spelling
    needs: check-out-repo
    uses: ./
    with:
      check_type: "spelling"
      error_min: 3

  urls-check:
    name: Check URLS
    needs: check-out-repo
    uses: ./
    with:
      check_type: "urls"
      error_min: 3

  quiz-format:
    name: Check quiz format
    needs: check-out-repo
    uses: ./
    with:
      check_type: "quiz_format"
      error_min: 0
