# Candace Savonen Mar 2022

name: Testing ottr-reports
on:
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repo: jhudsl/OTTR_Template
        fetch-depth: 0

    - name: Check spelling
      uses: ./
      with:
        check_type: "spelling"
        error_min: 3

    - name: Check URLs
      uses: ./
      with:
        check_type: "urls"
        error_min: 0

    - name: Check quiz formatting
      uses: ./
      with:
        check_type: "quiz_format"
        error_min: 0
